name: Webex Events Python Public API SDK

on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/webex-events
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: SocioEvents/webex-events-python-sdk
          ref: ${{ env.GITHUB_SHA }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          python -m pip install build twine
      - name: Build package & publish to pypi
        run: |
          python -m build
          twine check dist/*
          twine upload -r pypi dist/* -u __token__ -p ${{ secrets.PYPI_SECRET}}
